Baby button:
  phone number: "5555551234" #yo phone number
  network interface: "en0" #see readme
  carrier: "verizon" #yo carrier
  message: "Ding dong!" #The message
  arp source: "74:75:48:20:f3:cd" #find this using the sniffer, see readme
  email: "test@test.com" #A gmail email address
  password: "password" #A gmail email password